### ISSUE TITLE
getting an issue 

### ISSUE THREAD

**Issue by Saketh-Gurram** [haseeb-heaven/Gemini-Vision-Pro#2]
![image](https://github.com/user-attachments/assets/c2928e56-30b9-4ee8-acab-1f4fafbe4aa7)

Any idea on how to solve this issue 
I am using ubuntu 22.04

**Comment by haseeb-heaven** [comment]
PyAudio package is missing from your pc install that if you're running this locally

**Comment by Saketh-Gurram** [comment]
yeah got it thank you
